### ISSUE TITLE
SKPluginLibrary Configuration Exception

### ISSUE THREAD

**Issue by scotwoodyard-csulb** [HillPhelmuth/AdventuresInSemanticKernel#7]
When I run the project, I get the following error:

SkPluginLibrary.Reliability.ConfigurationNotFoundException
  HResult=0x80131500
  Message=Configuration section 'CoreSettings' not found
  Source=SkPluginLibrary
  StackTrace:
   at SkPluginLibrary.Models.TestConfiguration.LoadSection[T](String caller) in C:\Users\atsadmin1\Downloads\AdventuresInSemanticKernel-master\AdventuresInSemanticKernel-master\SkPluginLibrary\Models\TestConfiguration.cs:line 243
   at SkPluginLibrary.Models.TestConfiguration.get_CoreSettings() in C:\Users\atsadmin1\Downloads\AdventuresInSemanticKernel-master\AdventuresInSemanticKernel-master\SkPluginLibrary\Models\TestConfiguration.cs:line 207
   at SkPluginLibrary.Models.TestConfiguration.Validate() in C:\Users\atsadmin1\Downloads\AdventuresInSemanticKernel-master\AdventuresInSemanticKernel-master\SkPluginLibrary\Models\TestConfiguration.cs:line 57
   at SkPluginLibrary.Models.TestConfiguration.Initialize(IConfiguration configRoot) in C:\Users\atsadmin1\Downloads\AdventuresInSemanticKernel-master\AdventuresInSemanticKernel-master\SkPluginLibrary\Models\TestConfiguration.cs:line 22
   at Program.<Main>$(String[] args) in C:\Users\atsadmin1\Downloads\AdventuresInSemanticKernel-master\AdventuresInSemanticKernel-master\BlazorWithSematicKernel\Program.cs:line 14

**Comment by HillPhelmuth** [comment]
I assume you're running this locally. This error indicates that you're missing a required value either in `appsettings.json` or in user-secrets. For any of the examples to run it requires OpenAI or Azure OpenAI settings. To indicate which, you're using, you'll need a setting like `"CoreSettings:Service": "OpenAI"`. Depending on which you're using, the corresponding settings will be required. For OpenAI, the required settings are:
```json
"CoreSettings:Service": "OpenAI"
"OpenAI:ApiKey": "your-api-key",
// One of the following
"OpenAI:Gpt35ModelId": "gpt-4o-mini",
"OpenAI:Gpt4ModelId": "gpt-4o-2024-08-06"
```
or, for Azure OpenAI, it will look like:
```json
"CoreSettings:Service": "AzureOpenAI",
"AzureOpenAI:ApiKey": "your-api-key",
"AzureOpenAI:Endpoint": "your-resource-endpoint",
// One of the following
"AzureOpenAI:Gpt35DeploymentName": "",
"AzureOpenAI:Gpt4DeploymentName": ""
```
This is just the minimum to get started. I'll add a simple `appsettings.example.json` file with all the various settings so you can add them in the Configuration section of the application like you can in the published demo.
